### PR TITLE
several improvements

### PR DESCRIPTION
**Pull request by nightlyone**
and almost a small rewrite
* improve documentation (thank you gometalinter!)
* mark some errors as temporary
* Unlock only files we did lock (and report rogue filesystem activity)
* added a few helpers (and test them)

### CODE REVIEW

**Comment by Acconut** [comment]
Before this PR, even the process which created the lock was not able to obtain the same lock again, which was the behavior I relied upon (my usecase is that only one HTTP request is allowed to access a resource concurrently even if handled by the same Go process). However, with those changes applied (this added condition, https://github.com/nightlyone/lockfile/pull/15/commits/52f65c66c1c58b138f76f9c973f9e9b6efe0b2ca#diff-6e14b6c3c23e2021aa220c56ae4f1972R133, in particular) the owning process of a lock will happily obtain the lock again. This is a breaking change for me and sadly makes the package less easily to use, but still possible.

My main question is whether this behavior is actually wanted or not? I would be pleased to hearing  back from you.

**Comment by nightlyone** [comment]
I am sorry to hear that @Acconut and will take a look in the next few days. Then it will be either a documentation update or a bug fix. Not sure which it will be at the moment.

**Comment by Acconut** [comment]
@nightlyone Thank you a lot in advance :)

**Comment by nightlyone** [comment]
@Acconut I updated the package description to make it clearer.

You could build a special type ProcessLock combining a sync.Mutex with a lockfile.Lockfile like this: https://play.golang.org/p/yWRH-t9hPd

**Comment by Acconut** [comment]
@nightlyone Perfect, and thank you a lot for this example code. I will implement something similar pretty soon for my use case. In the meantime, would you be so kind and tag the commit before this PR landed (941fc61ce4d67dd432b94ed0bd445ad5fb9391a9) as `v1.0.0` so I am able to import the "old" package using http://labix.org/gopkg.in until I update my project? That would be very kind of you.

**Pull request merged**
