### PR TITLE
resolve #10

### LINKED ISSUE #10: Failer on windows when pid is from dead process
os: windows (tested on win10)

Reproduce:
1. Create lock file.
2. Exit process without cleaning up lock file. (as happens when you crash)
3. TryLock from new process.

This will produce `OpenProcess: The parameter is incorrect.` error, when it should succeed.

Cause:
```
func (l Lockfile) GetOwner() (*os.Process, error) {
	...
		p, err := os.FindProcess(pid)
		if err != nil {
			return nil, err
		}
	...
}
```

https://golang.org/pkg/os/#FindProcess

> On Unix systems, FindProcess always succeeds and returns a Process for the given pid, regardless of whether the process exists.  

But it's not documented for windows, and appears to return the error when process does not exit.

Fix:

We can assume that if the process exists, then FindProcess always succeeds in any operating system. There for, if FindProcess process returns an error, the process does not exist. So instead of returning the err, return ErrInvalidPid or ErrDeadOwner sould work here.

### PR DESCRIPTION
**Pull request by xiegeo**
Solves err on windows when pid is from dead process

### CODE REVIEW

**Comment by nightlyone** [comment]
What a about permission problems accessing the process is? Could you detect and handle them differently?

**Comment by xiegeo** [comment]
I will type assert to retrieve the underling error.

The actual windows api call in syscall.OpenProcess. is : 
```
	r0, _, e1 := Syscall(procOpenProcess.Addr(), 3, uintptr(da), uintptr(_p0), uintptr(pid))
	handle = Handle(r0)
	if handle == 0 {
		if e1 != 0 {
			err = error(e1)
		} else {
			err = EINVAL
		}
	}
	return
```
Where EINVAL is returned for dead processes. I can cast that to lockfile.ErrDeadOwner

**Comment by stewi1014** [comment]
You're checking for dead process in the TryLock function. This should be in the isProcessAlive function should it not?

**Comment by xiegeo** [comment]
@stewi1014 I'm checking for dead process in the GetOwner function, which is called by TryLock. os.FindProcess gives error in windows for dead processes, so there is no dead processes for isProcessAlive to check.

**Comment by stewi1014** [comment]
@xiegeo Exactly. Does that not indicate a problem with the structure of the program that you have to put things in places where they don't really seem to fit in order to make it work?

**Comment by xiegeo** [comment]
@stewi1014 I see what you mean. Ideally the test should be done in a *_windows.go file too. It really comes down to the cost of refactoring vs a small but out of place change.

**Comment by xiegeo** [comment]
closed since stewi1014's verison is in

**Pull request closed without merging**
